# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# GENERAL
set -g default-terminal "screen-256color"
set -g escape-time 0 # This is just some copium shit tbh
set -g mode-keys vi # Hell yeah
set -g cursor-style bar # GOAT, but gets replaced every time neovim opens
set -g base-index 1 
set -g renumber-windows on

# KEYBINDING TWEAKS
set -g mouse on
unbind r
bind r source-file ~/.tmux.conf
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
set -g prefix C-s

bind P if-shell "tmux has-session -t pomodoro 2>/dev/null" \
  "display-popup -E 'tmux attach-session -t pomodoro -r'" \
  "display-popup -E -w 30% -h 30% 'tmux new-session -d -s pomodoro \"~/scripts/pomodoro.sh\" && tmux attach-session -t pomodoro -r'"

# DESIGN TWEAKS
set -g window-status-format "#[fg=#625e5a]#I:#W "
set -g window-status-current-format "|#[fg=#c5c9c5]#I:#W| "

set -g status-position bottom
set -g status-style bg=default
set -g status-right ""
set -g status-justify absolute-centre

set -g cursor-colour "#c5c9c5"

set -g message-style "fg=yellow, bg=default"

set -g pane-border-style 'fg=#625e5a'
set -g pane-active-border-style 'fg=#c5c9c5,bold'

run '~/.tmux/plugins/tpm/tpm'
