# Basado en Kanagawa Dragon
[mgr]
preview_hovered = { fg = "#c4746e" }
preview_focused = { fg = "#c4746e" }

[status]
overall = { fg = "#c5c9c5", bg = "#181616"}
sep_left = {open="|", close="|"}
sep_right = {open="|", close="|"}

[selection]
active = { bg = "#223249" }
inactive = { bg = "#223249" }

[filetype]
folder = { fg = "#8ba4b0" }
regular = { fg = "#c5c9c5" }

[ui]
foreground = "#c5c9c5"
background = "#181616"

[mode]
normal_main = { fg = "#c5c9c5", bg = "#181616", bold = true }
normal_alt  = { fg = "#c5c9c5", bg = "#181616" }

select_main = { fg = "#181616", bg = "#c4746e", bold = true }
select_alt  = { fg = "#181616", bg = "#e46876" }

unset_main  = { fg = "#727169", bg = "#181616" }
unset_alt   = { fg = "#727169", bg = "#223249" }
